const SLACK_WEBHOOK_URL_PATH = '/T1RUJ063F/B08N38YAP7B/kzsZgiB2g39OgMXCuM995lbG'
const GOOGLE_FORM_KEY =
  '1FAIpQLSelP1jZFW6gQtsLSlOtaD7UKDUPeqfdYbLUGdHdX6vIOAThwA'
const GOOGLE_FORM_MAPPING_TIMESTAMP = 'entry.34343954'
const GOOGLE_FORM_MAPPING_TOPIC = 'entry.302384538'
const GOOGLE_FORM_MAPPING_APP = 'entry.536199007'
const GOOGLE_FORM_MAPPING_OPERATING_SYSTEM = 'entry.1717180794'
const GOOGLE_FORM_MAPPING_DEVICE_MODEL = 'entry.536951034'
const GOOGLE_FORM_MAPPING_MESSAGE = 'entry.9561956'
const GOOGLE_FORM_MAPPING_APP_VERSION = 'entry.156031897'
const TEST_SLACK_WEBHOOK_URL_PATH =
  '/T1RUJ063F/B08LLRLBY9M/KTKA3MIJfmjX4izWfgnjbRIM'
const TEST_GOOGLE_FORM_KEY =
  '1FAIpQLScLltvRe64VzMDRzOVjGtHWZ3KafLC2zzvkEoJfTzJkFd67OA'
const TEST_GOOGLE_FORM_MAPPING_TIMESTAMP = 'entry.34343954'
const TEST_GOOGLE_FORM_MAPPING_TOPIC = 'entry.302384538'
const TEST_GOOGLE_FORM_MAPPING_APP = 'entry.536199007'
const TEST_GOOGLE_FORM_MAPPING_OPERATING_SYSTEM = 'entry.1717180794'
const TEST_GOOGLE_FORM_MAPPING_DEVICE_MODEL = 'entry.536951034'
const TEST_GOOGLE_FORM_MAPPING_MESSAGE = 'entry.9561956'
const TEST_GOOGLE_FORM_MAPPING_APP_VERSION = 'entry.156031897'

export {
  SLACK_WEBHOOK_URL_PATH,
  GOOGLE_FORM_KEY,
  GOOGLE_FORM_MAPPING_TIMESTAMP,
  GOOGLE_FORM_MAPPING_TOPIC,
  GOOGLE_FORM_MAPPING_APP,
  GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
  GOOGLE_FORM_MAPPING_DEVICE_MODEL,
  GOOGLE_FORM_MAPPING_MESSAGE,
  GOOGLE_FORM_MAPPING_APP_VERSION,
  TEST_SLACK_WEBHOOK_URL_PATH,
  TEST_GOOGLE_FORM_KEY,
  TEST_GOOGLE_FORM_MAPPING_TIMESTAMP,
  TEST_GOOGLE_FORM_MAPPING_TOPIC,
  TEST_GOOGLE_FORM_MAPPING_APP,
  TEST_GOOGLE_FORM_MAPPING_OPERATING_SYSTEM,
  TEST_GOOGLE_FORM_MAPPING_DEVICE_MODEL,
  TEST_GOOGLE_FORM_MAPPING_MESSAGE,
  TEST_GOOGLE_FORM_MAPPING_APP_VERSION
}
