export const PASSPHRASE_WORD_COUNTS = {
  STANDARD_12: 12,
  STANDARD_24: 24,
  WITH_RANDOM_12: 13, // 12 words + 1 random word
  WITH_RANDOM_24: 25 // 24 words + 1 random word
}

export const VALID_WORD_COUNTS = [
  PASSPHRASE_WORD_COUNTS.STANDARD_12,
  PASSPHRASE_WORD_COUNTS.WITH_RANDOM_12,
  PASSPHRASE_WORD_COUNTS.STANDARD_24,
  PASSPHRASE_WORD_COUNTS.WITH_RANDOM_24
]

export const DEFAULT_SELECTED_TYPE = PASSPHRASE_WORD_COUNTS.STANDARD_12

export const PASSPHRASE_TYPE_OPTIONS = [
  { label: '12 words', value: PASSPHRASE_WORD_COUNTS.STANDARD_12 },
  { label: '24 words', value: PASSPHRASE_WORD_COUNTS.STANDARD_24 }
]
